// frontend/src/components/Searchbar/Searchbar.vue
<script setup>
import { distance } from 'fastest-levenshtein';
import { onBeforeMount, ref } from 'vue';

const wasteItems = ref([])
const searchInput = ref('');
const testItems = [
  "Plastpose", "Plastflaske", "Plastbeger", "Plastbestikk", "Plastemballasje",
  "Plastfolie", "Plastkork", "Mykplast", "Hardplast", "Isopor",
  "Bobleplast", "Engangsplast", "PP-plast", "PET-flaske", "LDPE-plast", "PVC-rør",

  "Papirpose", "Pappeske", "Avispapir", "Reklamepapir", "Kartong",
  "Melkekartong", "Eggekartong", "Toalettpapirrull", "Tegnepapir",
  "Konvolutt", "Bokomslag", "Bølgepapp", "Serviett", "Matpapir",

  "Glassflaske", "Metallboks", "Hermetikkboks", "Syltetøyglass",
  "Vinflaske", "Ølflaske", "Metallfolie", "Aluminiumsboks",
  "Aluminiumsfolie", "Stålboks", "Lokk i metall", "Lysestake i glass",
  "Speil", "Drikkeboks",
  
  "Mobiltelefon", "Datamaskin", "Nettbrett", "Lader", "Batteri",
  "Litiumbatteri", "LED-lyspære", "Halogenpære", "Lysrør",
  "Kabel", "Høyttaler", "Hodetelefoner", "Fjernkontroll", "Strømledning",

  "Klær", "Sko", "Gardiner", "Sengetøy", "Håndklær",
  "Veske", "Belte", "Ullklær", "Jeans", "Skinnjakke",
  "Pledd", "Dyne", "Teppe", "Lær",

  "Maling", "Sprayboks", "Lakk", "Kjemikalier", "Rengjøringsmiddel",
  "Løsemidler", "Neglelakk", "Neglelakkfjerner", "Lim", "Blekkpatron",
  "Printerblekk", "Medisiner", "Desinfeksjonsmiddel", "Oljefilter",

  "Matrester", "Banan", "Epleskrott", "Kjøttrester", "Brødskalk",
  "Eggeskall", "Kaffegrut", "Tepose", "Fiskebein", "Grønnsaksskrell",
  "Nøtteskall", "Potetskrell", "Skall fra sitrusfrukt",

  "Gressklipp", "Løv", "Kvister", "Greiner", "Jord",
  "Planter", "Blomster", "Ugress", "Busker", "Hageavfall",

  "Stearinlys", "Tannbørste", "Q-tips", "Bomullspads",
  "Engangshanske", "Bleie", "Bind", "Tampong", "Snus", "Sigarettsneip",

  "Sofa", "Stol", "Bord", "Kommode", "Skap",
  "Seng", "Madrass", "Teppe", "Speil", "Sykkel",
  "Barnevogn", "TV", "Høyttaler"
];
const result = ref([]);

const searchResults = (itemList) => {
    const sortedResults = new Map();
    const input = searchInput.value.toLowerCase();
    let score = 1000;
    for (let i = 0; i < itemList.length; i++) {
        if (itemList[i].length < input.length-2) continue;
        const test = itemList[i].toLowerCase();

        if (test === input) {
            score = 0; // Eksakt match (best mulig treff)
        } else if (test.startsWith(input)) {
            score = 1; // Prefiks-match
        } else if (test.includes(input)) {
            score = 2; // Delvis match
        } else {
            score = 3 + distance(input, test); // Fuzzy match
        }
    
        sortedResults.set(itemList[i], score) 
        
    }
    result.value = getSmallestKeys(sortedResults);
    console.log(sortedResults)
}

function getSmallestKeys(map, count = 5) {
  return [...map]
    .sort((a, b) => a[1] - b[1] || a[0].length - b[0].length) // Sort by value or length (ascending)
    .slice(0, count)             // Get first 'count' elements
    .map(([key]) => key);        // Extract keys
}

async function getWasteNames(){

    try {
        const response = await fetch("http://localhost:9876/waste/");
        wasteItems.value = response.json();
    }
    catch(error){
        console.log("Error fetching waste database!")
    }

}


onBeforeMount(() => {
    getWasteNames(); // loads the full list of names of waste items from the database
})

</script>

<template>
    <div>
        <input @keyup="searchResults(testItems)" type="text" v-model="searchInput" placeholder="Search..." />
        <span>{{ result }}</span>
    </div>
</template>

// frontend/sortify/app/component/searchbar/searchbar.tsx
"use client";
import { distance } from "fastest-levenshtein"
import { useState, useRef , useEffect} from "react"
import { InputAdornment, OutlinedInput, Popper, Paper, List, ListItem, ClickAwayListener } from "@mui/material"
import SearchIcon from "@mui/icons-material/Search"
import styles from "./searchbar.module.css"



export default function Searcbar(){

    const [wasteItems, setWasteItems] = useState<string[]>([]);

    useEffect(() => {
        const getWasteItems = async () =>{
            //const response = await fetch("http://localhost:9876/api/waste");

            //const data: { name: string }[] = await response.json();
            //const items = data.map(obj => obj.name)
            //console.log("data:",items)
            // setWasteItems(items);

        };
        getWasteItems();
    }, []);




    const [query, setQuery] = useState("")
    const itemList = wasteItems;
//     ["Plastpose", "Plastflaske", "Plastbeger", "Plastbestikk", "Plastemballasje",
//     "Plastfolie", "Plastkork", "Mykplast", "Hardplast", "Isopor",
//     "Bobleplast", "Engangsplast", "PP-plast", "PET-flaske", "LDPE-plast", "PVC-rør",

//     "Papirpose", "Pappeske", "Avispapir", "Reklamepapir", "Kartong",
//     "Melkekartong", "Eggekartong", "Toalettpapirrull", "Tegnepapir",
//     "Konvolutt", "Bokomslag", "Bølgepapp", "Serviett", "Matpapir",

//     "Glassflaske", "Metallboks", "Hermetikkboks", "Syltetøyglass",
//     "Vinflaske", "Ølflaske", "Metallfolie", "Aluminiumsboks",
//     "Aluminiumsfolie", "Stålboks", "Lokk i metall", "Lysestake i glass",
//     "Speil", "Drikkeboks",

//     "Mobiltelefon", "Datamaskin", "Nettbrett", "Lader", "Batteri",
//     "Litiumbatteri", "LED-lyspære", "Halogenpære", "Lysrør",
//     "Kabel", "Høyttaler", "Hodetelefoner", "Fjernkontroll", "Strømledning",

//     "Klær", "Sko", "Gardiner", "Sengetøy", "Håndklær",
//     "Veske", "Belte", "Ullklær", "Jeans", "Skinnjakke",
//     "Pledd", "Dyne", "Teppe", "Lær",

//     "Maling", "Sprayboks", "Lakk", "Kjemikalier", "Rengjøringsmiddel",
//     "Løsemidler", "Neglelakk", "Neglelakkfjerner", "Lim", "Blekkpatron",
//     "Printerblekk", "Medisiner", "Desinfeksjonsmiddel", "Oljefilter",

//     "Matrester", "Banan", "Epleskrott", "Kjøttrester", "Brødskalk",
//     "Eggeskall", "Kaffegrut", "Tepose", "Fiskebein", "Grønnsaksskrell",
//     "Nøtteskall", "Potetskrell", "Skall fra sitrusfrukt",

//     "Gressklipp", "Løv", "Kvister", "Greiner", "Jord",
//     "Planter", "Blomster", "Ugress", "Busker", "Hageavfall",

//     "Stearinlys", "Tannbørste", "Q-tips", "Bomullspads",
//     "Engangshanske", "Bleie", "Bind", "Tampong", "Snus", "Sigarettsneip",

//     "Sofa", "Stol", "Bord", "Kommode", "Skap",
//     "Seng", "Madrass", "Teppe", "Speil", "Sykkel",
//     "Barnevogn", "TV", "Høyttaler"
//   ];
    const [queryResult, setQueryResult] = useState<string[]>([])
    const [open, setOpen] = useState(false);
    const anchorRef = useRef(null);

    const handleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const newQuery = event.target.value;
        setQuery(newQuery);
        setOpen(true);
        setQueryResult(searchResults(query))
        console.log("Query updated:", newQuery);
    };

    function searchResults(query: String): string[]{
        if (query.length === 0) return [];
        const sortedResults = new Map();
        const input = query.toLowerCase();
        let score = 1000;
        for (let i = 0; i < itemList.length; i++) {
            if (itemList[i].length < input.length-2) continue;
            const test = itemList[i].toLowerCase();

            if (test === input) {
                score = 0; // Eksakt match (best mulig treff)
            } else if (test.startsWith(input)) {
                score = 1; // Prefiks-match
            } else if (test.includes(input)) {
                score = 2; // Delvis match
            } else {
                score = 3 + distance(input, test); // Fuzzy match
            }
            sortedResults.set(itemList[i], score)

        }

        return getSmallestKeys(sortedResults)
    };

    function getSmallestKeys(map: Map<string, number>, count = 5): string[] {
        return [...map.entries()]
            .sort((a, b) => a[1] - b[1] || a[0].length - b[0].length) // Sort by values in ascending order
            .slice(0, count) // Get the first `count` entries
            .map(([key]) => key); // Extract and return sorted keys
    };


    return (
        <div className={styles.searchbarWrapper}>
            <OutlinedInput
                type="text"
                value={query}
                placeholder="Søk..."
                fullWidth
                onChange={handleChange}
                onBlur={() => setTimeout(()=> setOpen(false), 200)}
                inputRef={anchorRef}
                startAdornment = {<InputAdornment position="start"><SearchIcon/></InputAdornment>}
                className={styles.searchbarContainer}
                sx={{
                    borderRadius: '40px',
                }}
            />
            <Popper open={open} anchorEl={anchorRef.current} placement="bottom-start" sx={{zIndex: 1000}}>
                <ClickAwayListener onClickAway={() => setOpen(false)}>
                    <Paper>
                        <List>
                            {queryResult.map((item) => (
                                <ListItem key={item}>
                                    {item}
                                </ListItem>
                            ))}
                        </List>
                    </Paper>
                </ClickAwayListener>
            </Popper>
        </div>
    )
}
